[package]
authors = ["Kevin King <kevin@krypt.co>"]
name = "pkcs11shim"
version = "0.1.0"

[dependencies]
base64 = "*"
hyper = "*"
lazy_static = "*"
libloading = "*"
rand = "*"
syslog = "*"

[lib]
crate-type = ["cdylib"]
name = "krpkcs11"
